name: Build postmarketOS (Oppo A37f)

on:
  workflow_dispatch:

jobs:
  build-pmos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies & QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip pipx python3-wheel qemu-user-static binfmt-support

      - name: Install pmbootstrap
        run: |
          pipx install git+https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Initialize pmbootstrap Configuration
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          mkdir -p ~/.config
          cat << 'EOF' > ~/.config/pmbootstrap.cfg
          [pmbootstrap]
          device = oppo-a37f
          ui = phosh
          user = user
          EOF
          yes "" | pmbootstrap init

      - name: Build postmarketOS Image
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          pmbootstrap install --no-fde --password 1234

      - name: Prepare Artifacts
        run: |
          mkdir -p output
          sudo cp -r ~/.local/var/pmbootstrap/images/. output/
          sudo chown -R $USER:$USER output/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pmos-oppo-a37f-image
          path: output/
          retention-days: 7
          
